version: "2"
services:
  license-analysis:
    build:
      context: .
    image: fabric8-analytics/license-analysis
    network_mode: bridge
    entrypoint:
      - /bin/entrypoint.sh
    environment:
      SERVICE_PORT: "6162"
      DATA_DIR: "/"
      MAJORITY_THRESHOLD: "0.6"
    ports:
      - "6162:6162"
